# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-20 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='hash_base_id',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
