# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-04 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0002_auto_20161120_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='offer',
            name='drop',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='sale',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='offer',
            table='offers',
        ),
    ]
