# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-10 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0004_auto_20161205_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=320, null=True)),
            ],
            options={
                'db_table': 'blacklist',
            },
        ),
    ]
