# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-12 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0006_auto_20161210_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
