# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-12 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0007_offer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
