# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-13 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0008_auto_20161212_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='remail',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
    ]
