# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-13 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0009_offer_remail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='lead',
        ),
        migrations.AddField(
            model_name='blacklist',
            name='email',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
    ]
