# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-13 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0010_auto_20161213_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
