# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-13 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0011_offer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='redemptionPeriod',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
