# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-13 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0012_auto_20161213_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='redemptionPeriod',
            new_name='updated',
        ),
    ]
