# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-16 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0013_auto_20161213_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='date_started',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
