# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0014_offer_date_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='last_email_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='phase',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='offer',
            name='stage',
            field=models.SmallIntegerField(default=1),
        ),
    ]
