# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-22 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0015_auto_20170117_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Setting',
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='done',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offer',
            name='phase',
            field=models.SmallIntegerField(default=0),
        ),
    ]
