# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-11 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0016_auto_20170122_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='last_email_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
